/**
 * Theme CSS generator — converts ThemeColors into CSS custom properties.
 */

import type { ThemeColors } from "./themes.js";

const CSS_HEADER = `/* cocapn theme — auto-generated by cocapn themes apply */\n`;

function hexToRgb(hex: string): { r: number; g: number; b: number } {
  const h = hex.replace("#", "");
  return {
    r: parseInt(h.substring(0, 2), 16),
    g: parseInt(h.substring(2, 4), 16),
    b: parseInt(h.substring(4, 6), 16),
  };
}

function rgba(hex: string, alpha: number): string {
  const { r, g, b } = hexToRgb(hex);
  return `rgba(${r},${g},${b},${alpha})`;
}

export function generateThemeCSS(colors: ThemeColors): string {
  const lines: string[] = [
    CSS_HEADER,
    ":root {",
    `  --bg:       ${colors.bg};`,
    `  --surface:  ${colors.surface};`,
    `  --surface2: ${colors.surface2};`,
    `  --border:   ${colors.border};`,
    `  --text:     ${colors.text};`,
    `  --muted:    ${colors.muted};`,
    `  --primary:  ${colors.primary};`,
    `  --primary2: ${rgba(colors.primary, 0.15)};`,
    `  --user-bg:  ${rgba(colors.primary, 0.12)};`,
    `  --user-bdr: ${rgba(colors.primary, 0.3)};`,
    `  --success:  ${colors.success};`,
    `  --danger:   ${colors.danger};`,
    `  --warn:     ${colors.warn};`,
    `  --radius:   8px;`,
    `  --font:     -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;`,
    `  --mono:     'SF Mono', 'Fira Code', 'Fira Mono', Menlo, Consolas, monospace;`,
    "}",
    "",
  ];
  return lines.join("\n");
}

export function generateThemeCSSFile(colors: ThemeColors, themeName: string): string {
  return generateThemeCSS(colors) + `/* Theme: ${themeName} */\n`;
}
